# Generated by Django 5.2.3 on 2026-06-20 01:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("notifications", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="notificationlog",
            name="channel",
            field=models.CharField(
                choices=[("whatsapp", "WhatsApp"), ("sms", "SMS"), ("email", "Email")],
                max_length=10,
            ),
        ),
    ]
