# Generated by Django 5.2.3 on 2026-06-20 01:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0002_staffeducation_clientserviceduration"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="preferred_channel",
            field=models.CharField(
                choices=[("whatsapp", "WhatsApp"), ("sms", "SMS"), ("email", "Email")],
                default="whatsapp",
                max_length=10,
            ),
        ),
    ]
