# Generated by Django 5.2.3 on 2026-06-19 13:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="SystemSettings",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("booking_slot_minutes", models.PositiveIntegerField(default=15)),
                ("booking_horizon_days", models.PositiveIntegerField(default=60)),
                ("minimum_notice_hours", models.PositiveIntegerField(default=2)),
                ("max_appointments_per_day", models.PositiveIntegerField(default=3)),
                ("max_appointments_per_week", models.PositiveIntegerField(default=3)),
                ("max_appointments_per_batch", models.PositiveIntegerField(default=3)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "System settings",
                "verbose_name_plural": "System settings",
                "db_table": "system_settings",
            },
        ),
    ]
